### ISSUE TITLE
Classoffering Primary Key

### ISSUE THREAD

**Issue by Scott123180** [Capping-CPCA/Database#129]
Hey I noticed that the primary keys for the classOffering table are currently `date` and `siteName`. If they expand in the future and they hold two classes at once at the same site at the same time then we can't store that in the current database.

Is it possible to add back `classID` and `curriculumID` as part of the composite key?

Thanks

**Comment by Dr-Crow** [comment]
We took that out on purpose. First Algozzine mentioned that, having a class at the same time and place will not happen. Additionally, if later down the road they rework how they do classes,  site can become In-House Classroom 1, or we can make the site table slightly different to account for that. 

Also, we change it because of how either Surveys or attendance app can drive the creation of class offerings.  The Surveys do not know always what the class and curriculum are, they just know the place and at what time they took it. So when the attendance goes to be filled out, it checks if there is a class offering that matches that site and time, and thus binds to it.  If not create a class offering.

Now for you it requires some more work to join more tables but that is trial thing to do. You got it and if you have trouble ask us for help!

**Comment by Scott123180** [comment]
Got it, thanks for the answer! :smile:
