### ISSUE TITLE
Classes table add ID instead of topicname as PK

### ISSUE THREAD

**Issue by blackjack26** [Capping-CPCA/Database#19]
Currently in the `classes` table, the primary key is `topicname`. I agree that it does make sense not to have multiple classes with the same `topicname`. But, the table should have a `classid` PK field that is auto-incremented and the `topicname` field should be UNIQUE but not the primary key.

This also makes URL encoding significantly easier so we don't have something like `/classes/view/Ages%20&%20Stages:%20Appropriate%20Expectations` and instead will have `/classes/view/1` when searching by the primary key.

| classid | topicname | description |
|:-------:|:------------:|:------------:|
| PK, AUTOINCREMENT | UNIQUE | - |

**This same thing is applicable to the `sites` table**

**Comment by Dr-Crow** [comment]
We are going to look this over and discuss it with the team. In reality, it does not affect the database in any major way, but in best practice this should not be done.

**Comment by blackjack26** [comment]
I just ran into an issue with the primary key being the name of the class. If I want to go in an edit what the name of the class is, this will violate foreign key constraints. So how it is now, once the class is made, it will have to keep that name forever.

**Comment by Dr-Crow** [comment]
Classes names can be updated and are not set forever. I would not recommend changing them, since if we use this database for over a couple years, you still would want that historical data. The best bet would be to make a new class, but if its just a typo then go a head a fix it. 

To solve this issue, all we need to do is add on update cascade to the foreign key constraints. This will trickle down the name changes to the correct tables. Still as I stated before we probably do not want to change the names all that often.  We might want some extra handling and checking on the classes names as they get inputted to avoid this possible issue down the line.

**Comment by blackjack26** [comment]
Sounds good, right now I've just disabled editing the name when the classes / sites are edited.

**Comment by Dr-Crow** [comment]
Other then typos, do you think the CPCA will want to change the name of the course? They might have need for new classes, which they can add, but I do not see another reason to change the name.

**Comment by blackjack26** [comment]
No, I can't think of any other reason besides typos they'd want to change the name.

**Comment by marcosb1** [comment]
@Dr-Crow where did we land on this?

**Comment by Dr-Crow** [comment]
Leave it with the name of the class and not an ID. But we need to implement an update cascade. The only time this should be used is if there was a typo in the class not change the name of an old class. @blackjack26 can we enforce that on the UI?

**Comment by CBadame** [comment]
@Dr-Crow @blackjack26 can this be closed, or does it still require further discussion?

**Comment by blackjack26** [comment]
This can be closed. I think we've decided it'll be okay

**Comment by CBadame** [comment]
Alright cool, just wanted to make sure.
