### ISSUE TITLE
Create view for participant information

### ISSUE THREAD

**Issue by vmjoseph** [Capping-CPCA/Database#23]
- [x] Include participant people id
- [x] first name 
- [x] last name
- [x] middle init
- [x] race
- [x] gender 
- [x] date of birth
- [x] notes 
- [x] attendance history 
- [ ] family member information
- [ ] link to intake/referral packet
- [ ]  status of student: inactive after 2 weeks (show inactive as of date) , if graduated, show graduation date

**Comment by marcosb1** [comment]
@vjoseph2 So the view is done. But we have a few questions about the requirements here.

1. The checklist specifies to include family member information as well as a link to the intake/referral packet. Is that absolutely necessary for your page. If it is then we can gladly put that in. If not we recommend that the information be split into two different views. For example, one containing [peopleId, firstName, lastName, middleInit, race, gender, DOB, notes, attendanceHistory] and another containing [peopleId, firstName, lastName, middleInit, familyMemberInfo, intakeInfo, ReferralInfo]. The reason for this is because if all of this info is in one view, that view will have duplicated information per join that we perform to make it, thus it might be cleaner to just split it up as specified.
2. In regards to attendance history, what exactly do you need? So far we include [classDate, classTopic, site, comments]. It would be helpful to see a picture of that page you showed me in class so we have a better reference. Is the 10.11.x.x IP updated?

Thanks.

**Comment by vmjoseph** [comment]
Hey Marcos:
1. The family informaiton is needed for the page, but feel free to put it in another view. Family information will be displayed on the participant search result page, so as previously stated, feel free to make another view.
2. For attendance history, we only need the last time they were active and in which class. If the participant has graduated, we would want to display that as a status. For example, if you are a participant:

Name: Marcos Barbieri
Status: active, last class: date/date/date || inactive as of date/date/date || inactive, graduated date/date/date
Notes: notes and stuff

To my knowledge, the development server should be updated, but if not here is an image:

![alt text](https://i.imgur.com/EaDTfph.png "Logo Title Text 1")

**Comment by Dr-Crow** [comment]
#LOVE #PEACE

**Comment by jrands** [comment]
updated in 00362196f556dee5261ccaa836774614ef234177
