### ISSUE TITLE
DB broken

### ISSUE THREAD

**Issue by Scott123180** [Capping-CPCA/Database#42]
Getting the same error message through pgAdmin III as PHP storm postgres connection

`Error encountered when performing Introspect schema public: ERROR: invalid internal value for enum: 37982.
ERROR: invalid internal value for enum: 37982
and 5 duplicate reports`

**Comment by Dr-Crow** [comment]
.......

**Comment by Scott123180** [comment]
idk what your elipses mean but this is a pic of the prompt I'm receiving. It started today in class.

It keeps on occurring on multiple machines and it's messing up the schema detection on my laptop so plz fix soon.


![error](http://foxweb.marist.edu/users/khg8c/error_pg.png)

**Comment by Scott123180** [comment]
Hey Jim I keep on getting the error message and it's affecting the database schema sync in my IDE. Any update on this? Thanks

**Comment by blackjack26** [comment]
@Dr-Crow  @Scott123180 

The issue is that the new `Coordinator` enum in **permission** has an `oid` of **38581** instead of **37982**. 

```sql
SELECT oid, * FROM pg_enum WHERE enumtypid = 'permission'::regtype;
```

| oid | enumtypid | enumsortorder | enumlabel |
|:----:|:----:| ----:|:---- |
| 38581 | 37980 | 1.5 | Coordinator |
| 37984 | 37980 | 2 | Facilitator |
| 37986 | 37980 | 3 | Administrator |
| 37988 | 37980 | 4 | Superuser |

Notice that the "Coordinator" `oid` seems out of place in respect to the others. That is because the `oid` should be **37982** (which was removed when changed from "User" to "Coordinator"). I think if we do the following, it should fix it:

```sql
UPDATE pg_enum SET oid = 37982 WHERE enumtypid = 'permission'::regtype AND enumlabel = 'Coordinator';
```


---
This is where I got the information from:
<https://jobs.zalando.com/tech/blog/the-perils-of-modifying-postgresql-system-catalogs/?gh_src=4n3gxh1>

**Comment by CBadame** [comment]
![image](https://user-images.githubusercontent.com/9902666/31899830-9fcc75e2-b7ea-11e7-8454-86049fdb8424.png)

It looks like `oid` cannot be modified by users. The source you provided suggests "changing the data type of the enum to `oid`,  update the `oid` values of the enum labels that cause the error to the values, and then changing the pg_attribute type back", but I want to run this by Jimmy before trying it.

**Comment by Dr-Crow** [comment]
Refer to #40 . The DB will be resourced tomorrow during capping, thus fixing the problem
