### ISSUE TITLE
Surveys.....

### ISSUE THREAD

**Issue by Dr-Crow** [Capping-CPCA/Database#50]
So, we need to link the Class Offering and Surveys tables.  This will provide the connection so you know what survey belongs to what class. From there you can get people and stuff like that. The only issue now is the a entry in the survey now requires topic name, date, site name.  This becomes problematic when we start to implement the python script the survey team has.  They will need to figure out some how what class offer the survey. Maybe we can ask the users to select what class there in and also get a time stamp? Originally, we had the idea of using the different google sheets IDs, but since you guys are just using one giant one we can't anymore. 

See #13  for development on stored procedure. Maybe we could off load some of the heavy lifting there?

**Comment by Scott123180** [comment]
You could auto generate a unique ID for each class and have the participants enter it in at the beginning of each class. 

I.E. generate a random base 64 id that is 8 characters long and then quickly check against the DB if it's in use. If not, then use that as a unique class id. It gets rid of the serializeability problem so that people aren't taking surveys for other classes (i.e. survey numeber 1, 2, 3, 4, ..., n) and the facilitators can link it up later.

**Comment by Dr-Crow** [comment]
We need to store when last updated the last updated time of the surveys and create a view of all available classes, times, dates.

**Comment by marcosb1** [comment]
resolved in 3080604b9589bfb56c6a62230bf69ec9d16116a5

**Comment by Dr-Crow** [comment]
There needs to be a view added and the stored procedure made still.

**Comment by Dr-Crow** [comment]
@marcosb1 do you want to take this? or?

**Comment by Dr-Crow** [comment]
@marcosb1 do you want to take this or ?

**Comment by marcosb1** [comment]
I did this its resolved in 3080604b9589bfb56c6a62230bf69ec9d16116a5 @Dr-Crow
