### ISSUE TITLE
Referral Functions and Participant Searches with Duplicate Names

### ISSUE THREAD

**Issue by jrands** [Capping-CPCA/Database#65]
Before adding participants, the procedures selfreferral and agencyreferral need to check if they already exist in the database. To do so, we do the following: 

```sql 
              PERFORM Participants.participantID FROM Participants
                                    WHERE Participants.participantID IN (SELECT People.peopleID
                                                                        FROM People
                                                                        WHERE People.firstName = fName AND People.lastName = lName AND People.middleInit = mInit) AND Participants.dateOfBirth = dob;
```

We check participants date of birth because it is the only way to distinguish between two participants with the same name. However, if a form is submitted with a null DOB, the function will fail. As far as we can tell, our options are:

1) Enforce a not null constraint on DOB
2) Simply only compare names  (making the system virtually useless for participants which share the same name)
3) (maybe?) Add error handling to these procedures and notify the user / prompt for some manual action when a participant with a duplicate name is trying to be entered. 

Any thoughts/ideas appreciated fam

**Comment by Dr-Crow** [comment]
I like 3, and that is what I was thinking about. This goes beyond your problem and is something we need to iron out. Since there might be someone with the same name and DOB. What do you do then???  

I was thinking when you call in to a credit card company or something, they ask for your name and probably grabs your number you are calling on. Then they ask you to verify the information like address, this might be for security but also for limiting down which user you really are. I think this is something the UI and the DB will have to work out. Maybe @algozine and @blackjack26  can add their input?

**Comment by CBadame** [comment]
@marcosb1 was @Dr-Crow's solution implemented in the changes last night?

**Comment by Dr-Crow** [comment]
This is being completed by a modal that @vjoseph2 is completing. The modal will pop up on clicking the submit button, always. It will display to the user and list of people to choose from. If they do not find the user they want/non are listed, there will be a create person button.
