### ISSUE TITLE
Stored Procedure for Creating Participants

### ISSUE THREAD

**Issue by CBadame** [Capping-CPCA/Database#7]

**Comment by Vesiix** [comment]
Needs testing @marcosb1 @CBadame @Dr-Crow @jrands

**Comment by jrands** [comment]
Looks good to me

However the way it is currently set up is that if a person exists in the Persons table with a first name, last name, and middle initial that matches the participant trying to be entered it will link to that foreign key rather than creating a new entry in the persons table. Is this what we want?
