### ISSUE TITLE
Change names to match DB updates

### ISSUE THREAD

**Issue by CBadame** [Capping-CPCA/Database#98]
- Enum PROGRAMTYPE should be called LOCATIONTYPE

- 'Sites' table should be called 'Locations'

Make sure to make any necessary changes in table creation sql, views, procedures, and documentation, and notify other teams of any changes they may need to make.

**Comment by Scott123180** [comment]
@CBadame 
I don't think these changes are necessary. Although they may be stylistically correct, implementing them would break the web app as more than just stored procedures and views rely on this. I think it's best to keep the DB and it's structure the same as we wrap up the project.

**Comment by CBadame** [comment]
This isn't something that we would be implementing anytime soon, hence why it was given the tags of "backlog" or "parking lot", the reason being because we are aware that it would have a negative effect on code in other parts of the project. But as you've stated previously, we want to try and enforce consistency throughout the application, so this is something that should be done at the very end of the semester if time permits.

**Comment by Dr-Crow** [comment]
That's why it has those labels. Addtional if you coding your part of the web app to rely on those names it should be a easy find and replace. If not, they you coded something wrong. As for the views and stored procedures that's on our end so don't worry about that. This might be in release 2 of the database. Were on release 1. Check out develop branch if you want to see what's going on/prepare for some changes.

**Comment by Scott123180** [comment]
@CBadame @Dr-Crow 
I'm going to request that you put an additional tag of "hold" in addition to "parking lot".

Issues relating to changing the structure of the database should be discussed with the stakeholders of the web application team first. Then, if agreed upon, the changes should announced and an implementation plan drawn up (relating to time of change, scope of change, testing plan, etc.).

Please do not move forward with this until both teams have properly communicated and agreed on any changes to be made.

I will tag who I think are the appropriate parties to discuss this with so that they are notified: @blackjack26 @evanmena @michellecrawley

**Comment by ghost** [comment]
There is no good time to make changes to the underlying db that break code. As long as these changes aren't coming the day of a deploy and everyone knows it's going to happen Find and Replace is a trivial amount of work. 

These changes are just semantic but seem to bring the DB spec closer to how things are actually used in WebApp, which I support.

**Comment by Scott123180** [comment]
#throwback
